### ISSUE TITLE
`ctx.routerPath` causes routes to fail path matches

### ISSUE THREAD

**Issue by dsmackie** [koajs/router#101]
node.js version: v14.4.0
npm/yarn and version: 6.14.5
`@koa/router` version: 9.3.1
`koa` version: 2.13.0

#### Code sample:

```js
const koa = require('koa');
const app = new koa();
const Router = require('@koa/router');
const router1 = new Router();
const router2 = new Router();

router1.get('/:id/query', async (ctx, next) => {
  console.log('first');
  next();
});

router2.get('/demo/query', async (ctx, next) => {
  console.log('second');
  next();
})

app.use(router1.routes())
app.use(router2.routes())
app.listen(3000);
```

#### Expected Behavior:

With a call to `/demo/query` it is expected that;

`router1` will match and `first` will be output to console
`router2` will match and `second` will be output to console

#### Actual Behavior:

`router1` does match and `first` is output to console
`router2` never matches.

#### Cause (which I am not sure how to fix):

1. GET made to `/demo/query`
- `ctx.path` = `/demo/query`
- `ctx.routerPath` = `undefined`
- Match path used is `ctx.path` since `ctx.routerPath` is `undefined` - ([router.js#L341](https://github.com/koajs/router/blob/master/lib/router.js#L341))
2. Check for router match to `/demo/query` - ([router.js#L342](https://github.com/koajs/router/blob/master/lib/router.js#L342))
- Router1 GET of `/demo/query` matches against regexp `/^(?:\/([^\/#\?]+?))\/query[\/#\?]?$/i` (`/:id/query`)
- `layerChain` populates `ctx.routerPath` to match previous path `/:id/query` ([router.js#L366](https://github.com/koajs/router/blob/master/lib/router.js#L366))
3. Check for next router match to `/demo/query`
- `ctx.path` = `/demo/query`
- `ctx.routerPath` = `/:id/query`
- Match path used is `ctx.routerPath` since `ctx.routerPath` is set - ([router.js#L341](https://github.com/koajs/router/blob/master/lib/router.js#L341))
3. Check for match to `/:id/query` - Match FAILS
- `/:id/query` does not match against Router2 regexp `/^\/demo\/query[\/#\?]?$/i` (`/demo/query`)
- There is no match so the app stops.

The issue is that `ctx.routerPath` is being set to the previous matched path and overrides `ctx.path` for matching. This only appears to cause an issue when a parameter route is used before a similar route without a parameter.

Unfortunately I do not know the codebase enough to provide a solution, but this issue is related to #92, #94 and #97. These issues identify that the problem did not exist in v8.0.8. `ctx.routerPath` was introduced in v9.0.0 and is when the issues started to be reported.

**Comment by niftylettuce** [comment]
This is a non-issue, you should instead have something like this:

```js
router1.get('/:id/query', async (ctx, next) => {
  console.log('first');
  next();
}, async (ctx, next) => {
 // ...
});
```

**Comment by dsmackie** [comment]
@niftylettuce You should go through #92, #94 and #97 also and close those since they are related to this exact situation. The reason I looked into this is because of the extended period those issues have been open.
