### ISSUE TITLE
When I use @koa/router and mysql,  and async/await I still get not found

### ISSUE THREAD

**Issue by hahei89** [koajs/router#119]
node.js version:  14

npm/yarn and version: 

`@koa/router` version: 10.0.0

`koa` version: 2.13.1

#### Code sample:

My router.js is here: 
```js
const sqls = require('../sql/index')

const router = require('@koa/router')({
  prefix: '/tabs'
})

router.get('/data', async (ctx, next) => {
  const data  = await sqls.getUserData()
  ctx.body = {
    data
  }
  await next()
})

```
My sql.js is here: 
```js
module.exports = {
  getUserData () {
    
    return new Promise((resolve) => {
      connection.query('SELECT * from user', function (err, result, fields) {
        resolve({
          err,
          result,
          fields
        })
      })
    })
  }
}
```
#### Expected Behavior:

I want to get data
#### Actual Behavior:

Actually I got 'not found '  by postman

**Comment by yeliex** [comment]
call `ctx.status = 200` to set response status specifically

**Comment by lagden** [comment]
@hahei89 

remove `await next()`

**Comment by 3imed-jaberi** [comment]
@hahei89, I checked your example with promise take more than 5s to resolve and it's work fine. please check your connection, mysql server, env ...

**Comment by peterver** [comment]
@hahei89 Apologies for commenting on an older discussion, but were the router.js and sql.js the only scripts in this project?

If so, don't forget to mount the router onto a koajs instance, eg:

```
import Koa from 'koa';

... insert code for router creation here

const app = new Koa();
app.use(router.routes());
app.use(router.allowedMethods());
app.listen(...);
```
