### ISSUE TITLE
Map object is empty in the context body

### ISSUE THREAD

**Issue by valorad** [koajs/router#120]
node.js version: v14.16.1

npm/yarn and version: 6.14.12

`@koa/router` version: @10.0.0

`koa` version: @2.13.1

#### Code sample:

```js
const map = new Map([
  ["a", "b"],
  ["c", "d"],
])

router.get(`/api`, async (ctx) => {
  ctx.body = map
})
```

#### Expected Behavior:

Front-end receives:
{
  "a:" "b",
  "c": "d"
}

#### Actual Behavior:

Front-end receives:
{}

#### Additional steps, HTTP request details, or  to reproduce the behavior or a test case:

Reproduction Repo:

https://codesandbox.io/s/investigation-koa-router-map-gzz6n?file=/src/index.js

**Comment by 3imed-jaberi** [comment]
@valorad, if you need support `Map` .. you can open an issue [here](https://github.com/koajs/koa/issues).

**Comment by 3imed-jaberi** [comment]
@niftylettuce, please close this issue
