### ISSUE TITLE
Not Implemented and Not Allowed error response docs example w/ Hapi Boom doesn't work

### ISSUE THREAD

**Issue by RavenHursT** [koajs/router#127]
node.js version: 
```bash
❯ node -v
v14.17.3
```

npm/yarn and version: 
```bash
❯ npm -v
6.14.13
```

`@koa/router` version:  `10.1.0`

`koa` version: `2.13.1`

#### Code sample:

Borrowed from https://github.com/koajs/router/blob/master/API.md#routerallowedmethodsoptions--function

```js
const Koa = require('koa');
const Router = require('@koa/router');
const Boom = require('boom');

const app = new Koa();
const router = new Router();

router.get('/ping', async ctx => {
  ctx.body = 'PONG!'
})

app.use(router.routes());
app.use(router.allowedMethods({
  throw: true,
  notImplemented: () => new Boom.notImplemented(),
  methodNotAllowed: () => new Boom.methodNotAllowed()
}));
app.listen(8080)
```

#### Expected Behavior:

Should "just work" and give me `501 NOT IMPLEMENTED` when I call a route that doesn't an HTTP method implemented

#### Actual Behavior:

500 Internal Error

Console output:
```
  TypeError: Boom.methodNotAllowed is not a constructor
```

#### Additional steps, HTTP request details, or  to reproduce the behavior or a test case:

```bash
curl -X POST -I http://localhost:8080/ping
```

**Comment by niftylettuce** [comment]
This is an issue with Boom.  Note that Boom is now `@hapi/boom` I think, and the usage is a bit different.

**Comment by RavenHursT** [comment]
@niftylettuce but I didn't get the coffee example above from hapi's docs.  As I noted, this is in _koa-router_'s docs 🤔

**Comment by niftylettuce** [comment]
can you submit a PR with fixes? would be super appreciated to help keep
docs up to date!!!

**Comment by RavenHursT** [comment]
Sure.. can we reopen this and I'll make a PR off it?

**Comment by niftylettuce** [comment]
just reference it in the commit message and stuff

**Comment by niftylettuce** [comment]
Thanks again!
