### ISSUE TITLE
Fork repo or normal repo

### ISSUE THREAD

**Issue by golopot** [koajs/router#15]
This repo is a "fork repo" instead of a "normal repo", there is a subtitle `forked from ZijianHe/koa-router` under the repo name, and a "This branch is 10 commits ahead of ZijianHe:master." thing. 

Is it intended to be a fork repo? Or do you want to change it to a normal repo by some means( https://stackoverflow.com/questions/16052477/delete-fork-dependency-of-a-github-repository) ?

**Comment by niftylettuce** [comment]
It is normal now, detached.
