### ISSUE TITLE
[fix] Match the right controller when multiple routes matches without calling next()

### ISSUE THREAD

**Issue by kravorkid** [koajs/router#168]
## Describe the bug

**Node.js version:** 
Node v16.15.1

**OS version:** 
MacOs Ventura Version 13.3.1 (a)

**Description:** 
When multiple routes match, the router doesn't seems to execute the right controller without calling `next()`.

## Actual behavior
When not calling `next()` it execute the first controller and don't pass through the second, when next() is called both controllers are executed

## Expected behavior
Without calling `next()` it should match the right route controller and execute it

**Edit** i've looked at the source code to see how it works under the hood i've seen the `exclusive` options that i have tested before on my use case but did not fit well with other of my controllers (that's an another story) but i have one question why execute the `mostSpecificLayer` should be an option ? 
As stated in the documentation [here](https://github.com/koajs/router/blob/master/API.md#multiple-middleware) if we want to execute multiple middleware we just have to chain them in the route definition

## Code to reproduce
Here a test i've written (for now i've found a workaround by calling my route `users/count` before the route `users/:id`)

```
  it('Matches right controller when multiple routes match', function (done) {
    const app = new Koa();
    const router = new Router({ prefix: '/users' });
    
    router
      .get('/:id', function (ctx, next) {
        console.log('executed')
        ctx.body = { id: true };
        // next();
      })
      .get('/count', function (ctx, next) {
        ctx.body = { count: true };
      })


      request(http.createServer(app.use(router.routes(), router.allowedMethods()).callback()))
      .get('/users/count')
      .expect(200)
      .end(function (err, res) {
        if (err) return done(err);
        expect(res.body).to.have.property('count', true);
        done();
      });
  })
  ```
## Checklist

- [x] I have searched through GitHub issues for similar issues.
- [x] I have completely read through the README and documentation.
- [x] I have tested my code with the latest version of Node.js and this package and confirmed it is still not working.

**Comment by sombriks** [comment]
hi @kravorkid did you found the solution or just  a workaround to avoid the bug? do you mind if i open a pull request for this issue in the future if needed?

**Comment by 3imed-jaberi** [comment]
Hello guys, you can archive the asked behavior by marking the `exclusive` option as true.

```js
    const router = new Router({ exclusive: true });
```
