### ISSUE TITLE
v11.0.2 is tagged as latest in npm, instead of v12.0.1

### ISSUE THREAD

**Issue by jaydenseric** [koajs/router#176]
Please make v12.0.1 the latest release in npm, as v11.0.2 is incorrectly tagged as latest.

Here is the result of running `npm outdated` in a project with a `@koa/router` v12.0.1 dependency installed:

<img width="574" alt="Screenshot 2023-10-24 at 12 14 09 pm" src="https://github.com/koajs/router/assets/1754873/01e43436-ca7f-4e2c-8c6d-79e015615c28">

It's confusing and frustrating.

**Comment by alopix** [comment]
This seems to have been fixed now: https://www.npmjs.com/package/koa-router?activeTab=versions
<img width="796" alt="image" src="https://github.com/koajs/router/assets/124467/29f20963-d796-4878-a74b-c6efc7428583">

**Comment by 3imed-jaberi** [comment]
Fixed
