### ISSUE TITLE
Async not working as expected. "Not Found" instantly.

### ISSUE THREAD

**Issue by spidgorny** [koajs/router#20]
node.js version: 12.8.1

npm/yarn and version: 6.10.2

`koa-router` version: 7.4.0

`koa` version: 2.6.2

#### Code sample:

```js
router.get('/async', async (ctx) => {
  return new Promise((resolve, reject) => {
    console.log('wait...');
    setTimeout(() => {
      ctx.ok('ok after 1s');
      console.log('resolve');
      resolve('asd');
    }, 1000);
  });
});
```

#### Expected Behavior:

the request should wait 1s before responding with either 'ok after 1s' or 'asd'

#### Actual Behavior:

instant response with "Not Found" although timeout is started and stopped as expected. But the results from the timeout not appearing in response since response is already output and connection closed (prematurely IMHO)

**Comment by jamesaspence** [comment]
Interesting that you have an async function and are not using await. But you need to pass the second parameter, `next`, and I'd remove the `async` as you're not using it. You can change your code to this:

```js
router.get('/async', (ctx, next) => {
  next();
  return new Promise((resolve, reject) => {
    console.log('wait...');
    setTimeout(() => {
      ctx.ok('ok after 1s');
      console.log('resolve');
      resolve('asd');
    }, 1000);
  });
});
```

**Comment by jamesaspence** [comment]
To clarify - this will run your code. If you want to return `ok after 1s` `ctx.ok` will not do it - I don't know where you got that from but to return a body you can use `ctx.body`.

**Comment by lichaozhy** [comment]
I guess the cause may just be some middlewares not calling ``return next()`` correctlly. Specially, the router middleware is an async function but parent middlewares are normal sync functions. I think you should check all of your middlewares has been called ``return next()`` strictly or not.

I often made mistakes like yours when I was young. Good luck~~

**Comment by fl0w** [comment]
So, I'm not sure what `ctx.ok` is, I'm assuming that's something custom you have (because it aint part of Koa).

Anyway, this works fine IMO:

```js
const Koa = require('koa')
const Router = require('@koa/router')

const app = new Koa()
const router = new Router()

router.get('/async', (ctx) => {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
        ctx.body = 'ok after 1s' // changed from unknown `ctx.ok`
        console.log('resolving')
        resolve()
    }, 1000)
  })
})

app
  .use(router.routes())
  .listen(8080)
```

```sh
$ time curl localhost:8080/async
ok after 1s
real	0m1.020s
user	0m0.006s
sys	0m0.006s
```

So, either the implementation of `ctx.ok` is broken, or you have a try-catch somewhere in the middleware chain which is swallowing the error thrown by mistake. `ctx.ok()` should throw a `TypeError` because it's not a function by the way - so if you simply mistook Koa api with something else you should see it, or you're catching that as well somewhere.

**Comment by spidgorny** [comment]
You are right, there was a middleware above which was not using async/await. I was trying to fix it in the wrong place. This is fixed now.
