### ISSUE TITLE
Documentation issue on npmjs.com

### ISSUE THREAD

**Issue by stefanpl** [koajs/router#26]
The documentation on [npmjs.com](https://www.npmjs.com/package/@koa/router) still contains the line `var Router = require('koa-router');`, but should require `'@koa/router'`.

I could not figure out where this is actually coming from, as the `API.md` in the github repo contains the correct code. I've gotta admit I haven't pushlished to npmjs so far.

Would be nice to see this put right. (This might also be a good time to replace those `var`s)

**Comment by niftylettuce** [comment]
I've version bumped to v8.0.1, this should close the issue.
