### ISSUE TITLE
Typescript (Types)

### ISSUE THREAD

**Issue by andrefedev** [koajs/router#35]
Hi guys, I have experience with Node for building clients (front-end), now I am building an api with Koa. We know that now Typescript is everywhere then because this repository like so many others Node is so little support for typescript types. Is it not recommended to use Typescript for the backend with Node..? Will there be native type support in Koa, Thank You.

**Comment by fl0w** [comment]
There are no plans currently to rewrite Koa in Typescript. Whether you chose use Typescript or not is irrelevant to the library Koa. If you want to use Typescript, go for it. There's [types available](https://www.npmjs.com/package/@types/koa) as expected from the community.

**Comment by fl0w** [comment]
Edit: *Oops, thought I was in Koa repo. You can ignore my (deleted) answer if you got a mail sent - but I think same applies, AFAIK there are no plans to rewrite Koa router in TS*

**Comment by smbkr** [comment]
There is a types package available for @koa/router:

`npm install --save-dev @types/koa__router`

**Comment by esetnik** [comment]
This was hard to find. Can the maintainers bring types into the project? I'd submit a PR if they're willing to accept it.

**Comment by niftylettuce** [comment]
I don't support TypeScript and don't plan on ever.  It's bad for the JavaScript community and open source maintenance imho.

**Comment by niftylettuce** [comment]
released to npm as v5.1.1

**Comment by niftylettuce** [comment]
actually I did not release this yet, there's a bug

**Comment by georgyfarniev** [comment]
@niftylettuce I strongly disagree, typescript has a lot of advantages and supported by serious companies. IMO including types is nothing but additional convenience for developers. I can help you to maintain them. Please include it :)

**Comment by niftylettuce** [comment]
If I include it in one repository, then I start to have to do it across others.  Less is better.  I am very sorry, but accepting "types" then requires me to publish updates to it to npm, which requires more of my time.  I would rather dedicate time to very pressing issues versus maintenance to support a multitude of syntaxes that compile to plain JavaScript.  I hope you understand.

**Comment by georgyfarniev** [comment]
@niftylettuce I understand that. Not big problem since DefinitelyTypes exists. Thank you for forking and supporting this package 🥇

**Comment by niftylettuce** [comment]
No problem.  You may also find interest in https://lad.js.org.  I just put up the demo at https://lad.sh and just released v1.0.0 LTS codename "Jack".

```sh
npm i -g lad
```

If you need me directly for any pressing `@koa` related issues, you can find me in the Lad or Koa Slack channels.

**Comment by georgyfarniev** [comment]
@niftylettuce thanks, I will take a look. I tried to use koa-ts-controllers today, then I realized that I want to implement it in functional style instead of decorators and DI, which is much easier to do in koa. Them I found that you forked router. Glad that you supporting it. I want to keep things as simple as possible, just like vue 3 did instead of using classes everywhere. FP rules!

**Comment by fedyk** [comment]
@niftylettuce big thanks for your efforts with supporting this project. 

From the scale of interest to this ticket, I’d suggest not to decline the idea with typescript. Moreover, it can be implemented as a test project on side branch or even gradually added(typescript does support plan javascript as well).

Also, the porting to typescript will create a traction, invite more people to learn and contribute to 'koa'. That can have a positive effect on the project evolution.

Here is example of porting another popular library https://github.com/reduxjs/redux/issues/3500. The task is definitely not easy one. But if it succeeded, and accelerates development.

If this comment brought some 👍, I’d happy to kick off porting to 'ts'

**Comment by niftylettuce** [comment]
I understand your comments @fedyk and thank you for them

**Comment by mcrawshaw** [comment]
Added doc PR to make the name of the types package a little more obvious https://github.com/koajs/router/pull/47
