### ISSUE TITLE
Issue with koa-session and ParameterizedContext

### ISSUE THREAD

**Issue by silenceisgolden** [koajs/router#39]
node.js version: v12.10.0

npm/yarn and version: 6.10.3

`koa-router` version: 8.0.5

`@types/koa__router` version: 8.0.2

`koa-session` version: 5.12.3

`@types/koa-session` version: 5.10.1

`koa` version: 2.11.0

#### Code sample:

TODO: @silenceisgolden - make repro

```bash
tsc --noEmit
```

#### Expected Behavior:

No errors in typescript compilation.

#### Actual Behavior:

```
src/controllers/session-controller.ts:26:7 - error TS2339: Property 'session' does not exist on type 'ParameterizedContext<any, RouterParamContext<any, {}>>'.

26   ctx.session.uid = user.id;
         ~~~~~~~

src/controllers/session-controller.ts:33:23 - error TS2339: Property 'session' does not exist on type 'ParameterizedContext<any, RouterParamContext<any, {}>>'.

33   const { uid } = ctx.session;
                         ~~~~~~~

src/utils/rotate-xsrf-middleware.ts:22:19 - error TS2339: Property 'session' does not exist on type 'ParameterizedContext<any, RouterParamContext<any, {}>>'.

22   const sid = ctx.session.uid;
                     ~~~~~~~

src/utils/validate-xsrf-middleware.ts:11:22 - error TS2339: Property 'session' does not exist on type 'ParameterizedContext<any, RouterParamContext<any, {}>>'.

11   const { id } = ctx.session;
                        ~~~~~~~
```

**Comment by silenceisgolden** [comment]
Issue is resolved by this comment: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/36161#issuecomment-555634427

**Comment by zacanger** [comment]
The TypeScript types aren't maintained in this package, that's an issue for the DefinitelyTyped repo.

**Comment by TheMrZZ** [comment]
Still definitely a problem. I've no idea how to fix this, and reverting to "@types/koa 2.0.50" when we are at the 2.11.3 version seems like a terrible idea.

**Comment by zacanger** [comment]
I would suggest taking that up again on the linked issue https://github.com/DefinitelyTyped/DefinitelyTyped/issues/36161 or putting in a PR on that project, since that's where the types are maintained.

**Comment by puzzledbytheweb** [comment]
Hey @TheMrZZ I had that issue and solved it by following this reply - https://github.com/DefinitelyTyped/DefinitelyTyped/issues/36161#issuecomment-571295417
