### ISSUE TITLE
Routing does not handle optional route parameter with prefix

### ISSUE THREAD

**Issue by smarts** [koajs/router#40]
node.js version: 
`13.3.0`

npm/yarn and version: 
npm `6.4.1`
yarn `1.19.2` (this is what i'm using)

`@koa/router` version: 
`8.0.5`

`koa` version: 
`2.11.0`
#### Code sample:

```js
const router = require('@koa/router')()
const Koa = require('koa')
// following line included to demonstrate difference in underlying library - version 6.1.0
const { pathToRegexp } = require("path-to-regexp")
const app = module.exports = new Koa()
const middleware = async (ctx, next) => { ctx.body = 'it worked'; return await next() }

const withoutIDRoute = '/foo{.:ext}?'
router.get('withoutID', withoutIDRoute, middleware)

app.use(router.routes()).use(router.allowedMethods())

console.log(pathToRegexp(withoutIDRoute).test('/foo.json')) // outputs true
console.log(pathToRegexp(withoutIDRoute).test('/foo')) // outputs true

app.listen(3080)
```

#### Expected Behavior:
- `http://localhost:3080/foo.json` returns `it worked` as a text response
- `http://localhost:3080/foo` returns `it worked` as a text response
- More generally, `@koa/router` matches routes that `path-to-regexp` matches (as documented in [this section](https://github.com/koajs/router/blob/master/API.md#routergetputpostpatchdeletedel--router))

#### Actual Behavior:
Both of the aforementioned URLs result in a 404 Not Found response

**Comment by smarts** [comment]
FYI i got this working by inlining the code for this package and updating the code to rely on the latest version of `path-to-regexp`. Is there any interest in a pull request w/ the update?

**Comment by niftylettuce** [comment]
If this is a bug a PR is welcome for sure

**Comment by smarts** [comment]
Thanks for replying @niftylettuce. Well, _I_ think it's a bug, but I don't know how to prove that w/o someone on the ownership team taking a look. However, I can confidently state that several bug fixes have gone into the underlying library (`path-to-regexp`) since the version that `@koa/router` relies on. It relies on 1.x and the current version is 6.1.0.

**Comment by niftylettuce** [comment]
Can you write a failing test case and submit it as a PR?  Based off your expected + actual behavior above?  Would be greatly appreciated as a lot of the legwork could be done for me in advance.

**Comment by smarts** [comment]
I'd be happy to, but the test script does not work on Windows.

**Comment by smarts** [comment]
@niftylettuce ☝🏽

**Comment by tigt** [comment]
Just got bit by this. Is there anything I can do to help — including donating?

**Comment by niftylettuce** [comment]
PR welcome with a version bump

**Comment by tigt** [comment]
@Sinewyk, thank you so much!

**Comment by niftylettuce** [comment]
v9.0.0 released to npm

https://github.com/koajs/router/releases/tag/v9.0.0

**Comment by Sinewyk** [comment]
Here's to hoping I didn't break something else.

**Comment by niftylettuce** [comment]
I deprecated v9.0.0 as I found core issues with it in my app

**Comment by smarts** [comment]
Since you deprecated v9.0.0 can you please reopen this @niftylettuce ?

**Comment by smarts** [comment]
Also, @niftylettuce did you or someone else who's an owner of this project take a look at the test case to verify that it's a legitimate bug?

**Comment by niftylettuce** [comment]
When I tested, there were several core routing issues with v9.x.

**Comment by smarts** [comment]
@niftylettuce I understand that, but this is still a bug... And sorry if this is what you were referring to, but [this comment](https://github.com/koajs/router/issues/40#issuecomment-623024104) was asking if you looked at #43 
That's the failing test you asked me to write. Are you preferring to close this issue in favor of that pull request?

**Comment by niftylettuce** [comment]
v9.0.1 is released.  See #43, please update PR and I will accept

**Comment by niftylettuce** [comment]
@smarts one moment, I'm going to have @3imed-jaberi look at that.
