### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by mahnunchik** [koajs/router#48]
Hi,

How to catch errors? The following code produces: `UnhandledPromiseRejectionWarning: BadRequestError: blabla`

```js
router.get('/', (ctx, next) => {
  ctx.throw(400, 'blabla')
});
```

node.js version: v12.14.1

npm/yarn and version: 6.13.4

`@koa/router` version: 8.0.6

`koa` version: 2.11.0

#### Code sample:

```js
router.get('/', (ctx, next) => {
  ctx.throw(400, 'blabla')
});
```

#### Expected Behavior:

Like without router

```js
app.use((ctx, next) => {
  ctx.throw(400, 'blabla')
});
```

Response `blabla` with 400 status code.

#### Actual Behavior:

(node:90487) UnhandledPromiseRejectionWarning: BadRequestError: balabla

**Comment by JacobMGEvans** [comment]
I will take a look at this when I get a minute.

**Comment by zacanger** [comment]
What versions of the libraries are you on, and do you have any other middlewares that could be affecting things? This minimal reproduction works as expected:

```javascript
const Koa = require('koa')
const Router = require('@koa/router')
const app = new Koa()
const router = new Router()
const port = 9999

router.get('/', (ctx) => {
  ctx.throw(400, 'oh no')
})

app.use(router.routes())

app.listen(port, () => {
  console.log(`listening on ${port}`)
})
```

**Comment by lagden** [comment]
You need an error handler...

Example:

```js
'use strict'

const Koa = require('koa')
const Router = require('@koa/router')

const port = 9999

// Middleware
function _error(emit = false) {
  return async (ctx, next) => {
    try {
      await next()
    } catch (error) {
      ctx.status = error.status || error.statusCode || 500
      ctx.body = {
        error: error.message
      }
      if (emit) {
        ctx.app.emit('error', error)
      }
    }
  }
}

// Routes
const router = new Router()
router.get('/', ctx => {
  ctx.throw(400, 'oh no')
})

// App
const app = new Koa()
app
  .use(_error(true)) // put _error middleware in first place
  .use(router.routes())
  .use(router.allowedMethods({throw: true}))
  .on('error', console.error)

app.listen(port, () => {
  console.log(`Listening on ${port}`)
})
```

**Comment by 3imed-jaberi** [comment]
@mahnunchik, I think the answers are enough .. I want to add that I checked your code and I didn't encounter any problem.
 if you still have this problem can you provide a complete example !!
