### ISSUE TITLE
Add throw option to the routes middleware

### ISSUE THREAD

**Issue by thewilkybarkid** [koajs/router#49]
The `allowedMethods` middleware has a `throw` option, I'd like to add the same to `routes`. For now I have a custom middleware (https://github.com/libero/article-store/blob/master/src/middleware/routing.ts), but it'd be great to have it built in.

**Comment by kravorkid** [comment]
You can use the `ctx.throw([status], [msg], [properties])` from koa here the full [documentation](https://koajs.com/#context)
