### ISSUE TITLE
Bench files not working properly (Improve Benchmark testing and usage)

### ISSUE THREAD

**Issue by JacobMGEvans** [koajs/router#52]
- nest() method seemed deprecated and was replaced by in the API so I used .middleware() seemed to handle the change ok. 
- I will create a separate PR with the benchmark code changes.  😃 

- [x] Initial Fix Bench files & add script in package.json
- [x] Update Bench folder 
- [x] Improve Bench server.js code _(could still refactor and improve more)_
- [x] Improve Makefile
- [x] Improve run shell file
- [x] Improve output, accuracy, and stability/consistency. _(no tests on benchmark code server.js)_

#51 is created, I am not sure but I think the server.js file can be improved for benchmark **accuracy and stability/consistency.**
_Originally posted by @JacobMGEvans in https://github.com/koajs/router/pull/50#issuecomment-581224198_

**Comment by niftylettuce** [comment]
I believe we can close this now?  Let me know - I merged both of your PR's - is it ready to cut a new release to npm for?

**Comment by JacobMGEvans** [comment]
- no tests on benchmark code server.js
- could still refactor and improve server.js more
