### ISSUE TITLE
Router.use() doesn't take in composed Router middleware as expected

### ISSUE THREAD

**Issue by meteorlxy** [koajs/router#53]
> It's just a quick mirror of https://github.com/ZijianHe/koa-router/issues/454, which is unresolved but closed.

node.js version: 10.16.0

npm/yarn and version: yarn 1.17.3

`@koa/router` version: 8.0.6

`koa` version: 2.11.0

`koa-compose` version: 4.1.0

#### Code sample:

```js
const app = new Koa();
const router1 = new Router();
const router2 = new Router();

router2.get('/', ctx => {
  ctx.body = 'not work';
});

router1.use('/', compose([router2.routes(), router2.allowedMethods()]));

app.use(router1.routes()).use(router1.allowedMethods());
```

#### Expected Behavior:

Visit `'/'`, get `'not work'`

#### Actual Behavior:

Visit `'/'`, get `'Not Found'`

**Comment by bb-user-01** [comment]
Same here. Spent an hour to find out `use..` was not composed as `app.use`. Tryied put put `'*'` or anyhing in the `use(path,...` but no luck. I am building a little app abstraction layer, so, I will use a different code path for the `use` and do a compose with the `router.routes()`. Would have been nice if it was just a way to put `.use` in an router (nothing more. nothing less).

**Comment by dominicegginton** [comment]
Can replicate the issue you are having, my solution, if you still need it, is to simply skip composing `router2.routes()` and `router2.allowedMethods()` together and pass them both into the `router1.use()` method:

``` js
const app = new Koa();
const router1 = new Router();
const router2 = new Router();

router2.get('/', ctx => {
  ctx.body = 'not work'
})

router1.use('/', router2.routes(), router2.allowedMethods())

app.use(router1.routes()).use(router1.allowedMethods())
```

**Comment by lagden** [comment]
@meteorlxy 

It's not necessary use `compose`.  
You can see the @dominicegginton example above.

I make this way to put my `routes` together (using `compose`):  
https://github.com/lagden/api-boilerplate/blob/master/server/routes/index.js

**Comment by meteorlxy** [comment]
@lagden 

Yeah, it's not necessary. But IMO, all middlewares of koa should work with `koa-compose` ? 🤔

**Comment by cmd-johnson** [comment]
I got `@koa/router` to work with `koa-compose` like this:
```js
const app = new Koa()
const router1 = new Router()
const router2 = new Router()

router2.get('/', ctx => {
  ctx.body = 'this works!'
})
const composed = Object.assign(
  compose([router2.routes(), router2.allowedMethods()]),
  { router: router2 }
)

router1.use('/', composed)
app.use(router1.routes()).use(router1.allowedMethods())
```

I'm pretty sure `middleware.router` belongs to the internal API of `@koa/router` and as such may be changed without notice, but for now this appears to be working perfectly fine.

**Comment by 3imed-jaberi** [comment]
@niftylettuce, please close this issue.
