### ISSUE TITLE
Use an alternative to hardcoded 3333 in Bench tests

### ISSUE THREAD

**Issue by JacobMGEvans** [koajs/router#56]
> @JacobMGEvans Could we use get-port as an alternative to hardcoded 3333? https://github.com/sindresorhus/get-port

@niftylettuce 
We could also potentially use .env https://github.com/motdotla/dotenv

which could also allow for more environment variables to be dynamic from Node defined in a local .env file process and with hardcoded fallbacks.

_Originally posted by @JacobMGEvans in https://github.com/koajs/router/pull/51#issuecomment-583921152_

**Comment by niftylettuce** [comment]
`@ladjs/env` is better (I made it too!)

https://github.com/ladjs/env

example usage https://github.com/ladjs/lad.sh or https://github.com/forwardemail/forwardemail.net

**Comment by niftylettuce** [comment]
@JacobMGEvans 	could you get this in too?  I just merged your other PR

**Comment by JacobMGEvans** [comment]
I'll probably work on this, this weekend

**Comment by niftylettuce** [comment]
❤️ 👍 🙇
