### ISSUE TITLE
npm project to use

### ISSUE THREAD

**Issue by joolfe** [koajs/router#59]
Hi, 
Normally this project had been published in [@koa/router](https://www.npmjs.com/package/@koa/router) in npm but i have seen that 3 days ago this exactly project has been also published in [koa-router](https://www.npmjs.com/package/koa-router) that is the deprecated project... witch npm project should we use as dependency?

Best Regards

**Comment by niftylettuce** [comment]
I maintain both, either is fine.

**Comment by joolfe** [comment]
Thanks!
