### ISSUE TITLE
Router GET with parameter and Nested Routes It's possible?

### ISSUE THREAD

**Issue by TrejoCode** [koajs/router#65]
Hi, have a problem with the routes, it is the following:

All courses: **Works**
``` console
/courses
```
Specific course: **Works**
``` console
/courses/1
```
Specific course with Nested Routes: **Doesn't work - 404**
``` console
/courses/1/levels
```
courses.js
``` js
const levels = require('./levels');

const route = new koaRouter({ 
    prefix: '/courses' 
});

route.get('/', koaBody(), async (context) => {
    // Some Logic
    context.body = { "Courses": "All" };
});

route.get('/:id', koaBody(), async (context) => {
    // Some Logic
    context.body = { "Course": "1" };
});

route.get('/:id/levels', levels.routes());
```

levels.js
``` js
const route = new koaRouter({ 
    prefix: '/levels' 
});

route.get('/', koaBody(), async (context) => {
    // Some Logic
    context.body = { "Courses Levels": "All" };
});
```

Can anybody help me?

**Comment by kravorkid** [comment]
your last `route.get('/:id/levels', levels.routes());` 
transform your `get` by a `use` and it should work

exemple extracted [from the documentation ](https://github.com/ZijianHe/koa-router#nested-routers)
`var forums = new Router();
var posts = new Router();

posts.get('/', (ctx, next) => {...});
posts.get('/:pid', (ctx, next) => {...});
forums.use('/forums/:fid/posts', posts.routes(), posts.allowedMethods());

// responds to "/forums/123/posts" and "/forums/123/posts/123"
app.use(forums.routes());`

Hope i've helped ;)

**Comment by TrejoCode** [comment]
> your last `route.get('/:id/levels', levels.routes());`
> transform your `get` by a `use` and it should work
> 
> exemple extracted [from the documentation ](https://github.com/ZijianHe/koa-router#nested-routers)
> 
> ```
> var forums = new Router();
> var posts = new Router();
> 
> posts.get('/', (ctx, next) => {...});
> posts.get('/:pid', (ctx, next) => {...});
> forums.use('/forums/:fid/posts', posts.routes(), posts.allowedMethods());
> 
> // responds to "/forums/123/posts" and "/forums/123/posts/123"
> app.use(forums.routes());
> ```
> 
> Hope i've helped ;)

Thank you, i'll try and and tell you

**Comment by TrejoCode** [comment]
Works, using:
```route.use('/:id', levelsRoutes.routes());```

Example:

```
const levels = require('./levels');

const route = new koaRouter({ 
    prefix: '/courses' 
});

route.get('/', koaBody(), async (context) => {
    // Some Logic
    context.body = { "Courses": "All" };
});

route.get('/:id', koaBody(), async (context) => {
    // Some Logic
    context.body = { "Course": "1" };
});

// Endpoint for /levels
route.use('/:id', levelsRoutes.routes());

```

Thank you, seems strange because i need 'repeat' the same route.

**Comment by kravorkid** [comment]
You don't have to repeat yourself the levels router handle his own business, here i have maid an explicit exemple below

```
const users = new Router({ prefix: '/users' })
const levels = new Router({ prefix: '/levels' })

users.get('/', async (ctx, next) => {
  ctx.body = 'users root'
})

levels.get('/', async (ctx, next) => {
  ctx.body = 'levels root'
})

levels.get('/:id', async (ctx, next) => {
  ctx.body = `level ${ctx.params.id}`
})

users.use(levels.routes(), levels.allowedMethods())
```

**Comment by TrejoCode** [comment]
> You don't have to repeat yourself the levels router handle his own business, here i have maid an explicit exemple below
> 
> ```
> const users = new Router({ prefix: '/users' })
> const levels = new Router({ prefix: '/levels' })
> 
> users.get('/', async (ctx, next) => {
>   ctx.body = 'users root'
> })
> 
> levels.get('/', async (ctx, next) => {
>   ctx.body = 'levels root'
> })
> 
> levels.get('/:id', async (ctx, next) => {
>   ctx.body = `level ${ctx.params.id}`
> })
> 
> users.use(levels.routes(), levels.allowedMethods())
> ```

Thank you, i'll try.
