### ISSUE TITLE
Why not use const replace var?

### ISSUE THREAD

**Issue by gaoxuerong** [koajs/router#74]
Why not use const replace var?🤔

**Comment by zacanger** [comment]
@niftylettuce since `engines` is 8+, this wouldn't be a breaking change. I'd be happy to run through and switch off `var` everywhere, I already did that on my fork back when there was that drama with koa-router getting sold.

**Comment by zacanger** [comment]
Switching to const, v8 can possibly do some tiny optimizations. Between let and var, there's no difference except in the case of C-style for loops. https://stackoverflow.com/questions/40070631/v8-javascript-performance-implications-of-const-let-and-var
