### ISSUE TITLE
How to reroute a request

### ISSUE THREAD

**Issue by theoephraim** [koajs/router#84]
Looking for some guidance on how to "reroute" a request from a route handler. Basically I'd like to have a route that makes some adjustments to the request (change `ctx.url`) returns control back to the router to try to find another matching route.

Express had a concept of calling `next('route')` to do something like this, but I can't find anything similar int the docs. Is this supported?

Thanks!

Update - looks like I can accomplish this in a route like this, but it feels hacky
```
ctx.method = newMethod;
ctx.url = newUrl;
ctx.request.body = newBody;
await ctx.router.routes()(ctx, next);
```

ALSO - interestingly, if I use a named param handler in the route that is trying to redirect to another, then this solution above does not work. It will call the route correctly, but execution of the middleware stack jumps ahead.

**Comment by theoephraim** [comment]
Just a quick update in case anyone else comes across this. I was able to get the router to run another route properly, including other named param handlers, but you must reset some items on ctx first. Here is an example:
```
router.get('/run-another-route', async (ctx, nex) => {

  // change the method/url etc
  ctx.method = 'post';
  ctx.url = '/another-route';
  ctx.request.body = { foo: 1 };

  // need to reset the ctx a bit or the router wont run properly for the new route
  ctx.status = 200;
  ctx.routerPath = undefined;
  ctx.captures = undefined;
  ctx.params = undefined;

  // re-run the router middleware as if we received the modified request
  await ctx.router.routes()(ctx, next);
}
```

**Comment by dominicegginton** [comment]
@theoephraim Thank you for your solution.

@niftylettuce Can you please close this issue?

**Comment by theoephraim** [comment]
I think it would still be useful to have something like built in, like express has `next('route')`
