### ISSUE TITLE
Version 9 is not published

### ISSUE THREAD

**Issue by ajimix** [koajs/router#86]
At some point, version 9 was published in npm: https://www.npmjs.com/package/@koa/router

But now is not available anymore. Can it be pushed again?

**Comment by niftylettuce** [comment]
I will have an update for you soon, I believe @3imed-jaberi can help out here 🎉

**Comment by niftylettuce** [comment]
v9.0.1 released https://github.com/koajs/router/releases/tag/v9.0.1
