### ISSUE TITLE
Issue with dependency 

### ISSUE THREAD

**Issue by danieldahan** [koajs/router#88]
node.js version: v12.16.3
`@koa/router` version: latest
`koa` version: latest

Hi! 

Not sure if you seen this error before, but it seems that building with your latest causes this weird issue. Any advice on this would be helpful. Thank you! 

<img width="646" alt="Screen Shot 2020-06-01 at 12 14 20 PM" src="https://user-images.githubusercontent.com/9982123/83446072-58d26380-a40b-11ea-8ba0-ea55661bc02f.png">

**Comment by niftylettuce** [comment]
We don't support TypeScript

**Comment by danieldahan** [comment]
And that makes sense. Cool, thank you!
