### ISSUE TITLE
404 error when defining routes: Does order matter in defining routes? 

### ISSUE THREAD

**Issue by julioagueros** [koajs/router#92]
node.js version: v11.3.0

npm/yarn and version: 6.14.5

`@koa/router` version: 7.4.0

`koa` version: 2.5.2

#### Code sample:

in my routes file I have this 
```
router.get('/entity/:id', ApiClass.getById);
router.post('/entitylist', ApiClass.getList);
router.get('/entity/number/:number', ApiClass.getId);
```

If I try to add a new route (so it looks like below) the last API (`/entity/status/`) doesn't get picked up and I end up with a 404 error.
```
router.get('/entity/:id', ApiClass.getById);
router.post('/entitylist', ApiClass.getList);
router.get('/entity/number/:number', ApiClass.getId);
router.get('/entity/status/', ApiClass.getStatus);
```

However, if I set it at the beginning of these set of routes (like below) it works just as expected.

```
router.get('/entity/status/', ApiClass.getStatus);
router.get('/entity/:id', ApiClass.getById);
router.post('/entitylist', ApiClass.getList);
router.get('/entity/number/:number', ApiClass.getId);
```

My question: is the order a factor in whether routes are well defined? what is the correct order for these definitions?

**Comment by envelope** [comment]
Yes, order is a factor - [it matches first to last](https://github.com/koajs/router/blob/5b6d4ea7b42a28326969742e865f89e9cb71ab84/test/lib/router.js#L224).

In your first example: the `id` parameter picks up the `status` part of the path, and hence it stops looking for other routes to match.

If you really need to keep the order, it is possible, but I _wouldn't_ recommend it in this case.
```JavaScript
// This route will only match if the `id` parameter is an integer
router.get('/entity/:id(\\d+)', ApiClass.getById);
```

@koa/router uses [path-to-regexp](https://github.com/koajs/router/blob/5b6d4ea7b42a28326969742e865f89e9cb71ab84/package.json#L15) to parse route paths into regular expressions. If interested, you can read about "custom matching parameters" in the [readme](https://github.com/pillarjs/path-to-regexp#custom-matching-parameters) 🙂
