### ISSUE TITLE
middleware do not execute

### ISSUE THREAD

**Issue by cheneyweb** [koajs/router#94]
node.js version: v14.4.0

npm/yarn and version: 6.14.5

@koa/router version: 9.1.0

koa version: 2.13.0

Code sample:

router1.get('/user/query', async (ctx, next) => {
console.log('before')
})
router2.get('/:demo/query', async (ctx, next) => {
console.log('middle')
})
router3.get('/user/query', async (ctx, next) => {
console.log('after')
})

app.use(router1)
app.use(router2)
app.use(router3)

With koa-router v8.0.8,  it work fine, it print
before
middle
after

But with koa-router v9.1.0,  it print

before
middle

what should I do for the same result as v8.0.8

**Comment by 3imed-jaberi** [comment]
You need to use the 'routes' in the 'app.use' level and 'next' in the router handler level and it should work fine!

```js
router1.get('/user/query', async (ctx, next) => {
console.log('before')
next()
})
router2.get('/:demo/query', async (ctx, next) => {
console.log('middle')
next()
})
router3.get('/user/query', async (ctx, next) => {
console.log('after')
next()
})

app.use(router1.routes())
app.use(router2.routes())
app.use(router3.routes())

// now, you should see in the console
  // before
  // middle
  // after
```
