### ISSUE TITLE
post method not allowed

### ISSUE THREAD

**Issue by CangJL** [koajs/router#96]
`const Koa = require('koa');
const Router = require('@koa/router')
const Boom = require('boom');

const app = new Koa();
const router = new Router();

router.get('/',ctx => {
  console.log(ctx)
  ctx.body = "Hello World";
});

router.get('/user/:id',ctx => {
    ctx.body = `Hello user ${ctx.params.id}`;
});

//no post method
router.post('/user',ctx => {
    ctx.body = `create a user`;
})

app.use(require('koa-bodyparser')())
app.use(router.routes())
app.use(router.allowedMethods({
  throw: true,
  notImplemented: () => Boom.notImplemented(),
  methodNotAllowed: () => Boom.methodNotAllowed()
}));

app.listen(3000)`

1.router has no post method
2.demo with boom needs update from 'new Boom.notImplemented()' to 'Boom.notImplemented()'

**Comment by gigenthomas** [comment]
I have the same issue - post fails for a registered route with message "Method Not Allowed"

**Comment by envelope** [comment]
Which version of `koa` and `@koa/router` are you using? I'm _not_ able to reproduce it with the following:
- `koa` v2.13.0
-  `@koa/router` 9.3.1
- `koa-bodyparser` 4.3.0
- `boom` 7.3.0

**Comment by 6613974** [comment]
I have the same problem, the latest version or the version you mentioned has the same problem.
The demo actually works
results：

router.get('/' xxxxxx)  [true]
router.post('/api',xxxxxx) [false]

router.get('/'xxxxx).post('/api','xxxxxxxx') [true]

Only the GET method exists

**Comment by 6613974** [comment]
demo:
```
const Koa = require('koa');
const router = require('@koa/router')()

const app = new Koa();


router.post('/',ctx =>{
    ctx.body = "112233"
})


app.use(router.routes())
app.use(router.allowedMethods())

app.listen(3000);

```

**Comment by 3imed-jaberi** [comment]
@CangJL, it's work fine with the latest release (10.x.x).
@niftylettuce, please close this issue.
